name = "PlanarInteractive"
uuid = "482fd972-58d7-43f2-aa46-1266790cbdd8"
authors = ["zbc"]
version = "0.1.0"

[deps]
Metrics = "3fcce980-bff0-41b4-8aec-9cac67d74284"
Optim = "01837fd2-c099-442f-ae89-75fa208aad36"
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Planar = "646fb1a4-6797-441d-ad18-3bdbde2eb86b"
Plotting = "8ada5bfb-e60b-44be-8979-616e14670061"
Scrapers = "38b379f7-ca41-4278-b0dc-774ced1e32bb"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"
